### ISSUE TITLE
RateLimiter.closePeriod - new method block any new permits for the given period

### ISSUE THREAD

**Issue by walec51** [resilience4j/resilience4j#1228]
There are situation when despite using a RateLimiter the underlining called service will say that you passed the maximum number of calls for a given period. For example an application that uses RateLimiter for its calls to a REST API can be restated and in consequence be not aware of the number previous calls done to that API. In this case despite having a properly defined RateLimiter config in accordance to the documented REST API call limit quota it can cause and over usage of the API. When that happens it would be good to close the current period in a given rate limiter so that no new permissions will be granted during it.

To achieve this I propose to add two methods:

```
rateLimiter.closePeriod();
```

and a configuration option that would close the period in a decorated call would throw an exception that meets some configured criteria

```
RateLimiterConfig.from(...)
                .limitRefreshPeriod(Duration.ofMinutes(1))
                .limitForPeriod(1200)
                .closePeriodOnException(e -> e instanceof HttpStatusAware && ((HttpStatusAware) e).getHttpStatus() == 429)
                .build()
```

I'm willing to prepare a pull request if this was to be accepted.

**Comment by RobWin** [comment]
Hi,

what do you think about calling it the new method:

`rateLimiter.drainPermissions()`

The method acquires and returns all permits that are available. Like `reservePermission`, but without a "number of permits" parameter.

I wonder if we should allow to the user to configure a result handler (`Either<Throwable,T> result`) so that he can even change other config parameters dynamically, eg. by using `rateLimiter.changeLimitForPeriod(newLimit)`. We could even utilize the existing event publisher and introduce a new `RateLimiterOnResultEvent`.

```
rateLimiter.getEventPublisher().onResult(event -> {
            Either<Throwable, T> result = event.getResult();
            // check result
            if(... ){
                rateLimiterRegistry
                    .rateLimiter(event.getRateLimiterName()).drainPermissions();
            });
        });
```

But indeed a short cut would be nice.

RateLimiterConfig.from(...)
                .limitRefreshPeriod(Duration.ofMinutes(1))
                .limitForPeriod(1200)
                .drainPermissionsOnException(e -> e instanceof HttpStatusAware && ((HttpStatusAware) e).getHttpStatus() == 429)

**Comment by walec51** [comment]
ok, I'll use `drainPermissions` and `drainPermissionsOnResult`
