### ISSUE TITLE
resilience4j-spring-boot2 annotation does not works alongside spring-boot-starter-quartz

### ISSUE THREAD

**Issue by quim3ra** [resilience4j/resilience4j#1296]
Resilience4j version: 1.6.1

Java version: java15

We have setup our project with `resilience4j-spring-boot2:1.6.1` to be used inside a job running within spring-boot-starter-quartz

The configuration is plain simple right now:

```
resilience4j.retry.configs.default.maxRetryAttempts     = 5
resilience4j.retry.configs.default.waitDuration         = 100
resilience4j.retry.configs.default.retryExceptions      = java.util.concurrent.TimeoutException
resilience4j.retry.instances.ThreeTimesRetry.baseConfig = default
```

And in one of our services that are running under a quartz job we have put the annotation to a method:

```
@Retry(name = "ThreeTimesRetry")
	public void dummyMethod() throws TimeoutException {
	   new TimeoutException("Dummy exception");
	}
```

Looks like because quartz job is running in a different thread, the global resilient4j configuration is not being picked up. Any way to overcome this?

Thanks!

**Comment by RobWin** [comment]
Hi,
what is your goal? 

I think you should not use Resilience4j if you want to retry the whole job.
You should use the capabilities of Quartz to schedule a retry attempt.

Have a look at this:
https://github.com/jasonesteele/quartz-demo/blob/master/src/main/java/sss/quartz/jobs/RetryJobWrapper.java

If you want to retry because of a temporary error, you can also use the functional style of Resilience4j instead of using annotations, which require that you Job is a Spring Bean.

**Comment by cbelizone2y** [comment]
> Hi,
> what is your goal?
> 
> I think you should not use Resilience4j if you want to retry the whole job.
> You should use the capabilities of Quartz to schedule a retry attempt.
> 
> Have a look at this:
> https://github.com/jasonesteele/quartz-demo/blob/master/src/main/java/sss/quartz/jobs/RetryJobWrapper.java
> 
> If you want to retry because of a temporary error, you can also use the functional style of Resilience4j instead of using annotations, which require that you Job is a Spring Bean.

Our job is connecting to an external API, and we simply want to ensure a retry in case the API timeouts, not the whole job, that's why we wanted to use resilient4j.
