### ISSUE TITLE
maxRetryAttempts not working as expected

### ISSUE THREAD

**Issue by kiararip91** [resilience4j/resilience4j#1320]
Resilience4j version:
1.3.1
Java version:
1.8

Hi there I have configured a method to be retried 2 times, I have put a log inside that method but I only see it executed 2 times, I was expecting that after the first failure 2 more executions where happening (so method executed 3 times in total).

Is the maxRetryAttempts params supposed to work like this? In this case it would be sort of maxAttempts instead of maxRetryAttempts correct?

``  retry:
    instances:
      dailyDataMigration:
        maxRetryAttempts: 2
        waitDuration: 100
``

``    @CircuitBreaker(name = MIGRATION_SERVICE)
    @Retry(name = MIGRATION_SERVICE, fallbackMethod = "testFallback")
    public MigrationData getMigrationStatus(int propertyId) {
        LOGGER.warn("--------------Inside getMigrationStatus------------------"); //THIS IS PRINTED 2 TIMES (I WAS EXPECTING TO SEE THIS PRINTED 3 TIMES)
       THIS WILL ALWASY FAIL
}``

**Comment by kiararip91** [comment]
hi guys any updates/clarification on this? thank you

**Comment by RobWin** [comment]
Hi,
yes, you are right it's confusing. I wonder why we forgot to add JavaDoc for  [maxAttempts](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-retry/src/main/java/io/github/resilience4j/retry/RetryConfig.java#L192) and 
`waitDuration` in `RetryConfig`.

`maxAttempts` is the total number of attempts, including the first failed call. That means `maxAttempts=3` results in 3 calls, if every call fails.

Because of the naming issue, we deprecated `maxRetryAttempts` in Spring Boot and renamed it to `maxAttempts`:
See: https://github.com/resilience4j/resilience4j/blob/03253134ac6f88954c8a65faa6dd7f92ed5e02f1/resilience4j-framework-common/src/main/java/io/github/resilience4j/common/retry/configuration/RetryConfigurationProperties.java#L363

**Comment by kiararip91** [comment]
Hi @RobWin thanks for your answer, I tried to use maxAttempts instead in the retry configuration but is ignoring that value and is retrying twice (maxAttempt = 3 as Default).
This is my config, am I missing something?
![image](https://user-images.githubusercontent.com/9994164/106464998-b1c23200-6499-11eb-8096-22e548c3dcca.png)

**Comment by RobWin** [comment]
Which version of resilience4j are you using?

**Comment by kiararip91** [comment]
I am using and it seems that 1.3.1 is the last version for this resilience4j-spring-boot https://mvnrepository.com/artifact/io.github.resilience4j/resilience4j-spring-boot

**Comment by RobWin** [comment]
Ok, you still have to use Spring Boot 1.x?
We don't maintain Spring Boot 1 anymore only Spring Boot 2.

**Comment by Romeh** [comment]
ok closing the ticket as nothing more is required from our side , feel free to open new issue if you have new questions

**Comment by Pranitan-witt** [comment]
> Hi, yes, you are right it's confusing. I wonder why we forgot to add JavaDoc for [maxAttempts](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-retry/src/main/java/io/github/resilience4j/retry/RetryConfig.java#L192) and `waitDuration` in `RetryConfig`.
> 
> `maxAttempts` is the total number of attempts, including the first failed call. That means `maxAttempts=3` results in 3 calls, if every call fails.
> 
> Because of the naming issue, we deprecated `maxRetryAttempts` in Spring Boot and renamed it to `maxAttempts`: See:
> 
> https://github.com/resilience4j/resilience4j/blob/03253134ac6f88954c8a65faa6dd7f92ed5e02f1/resilience4j-framework-common/src/main/java/io/github/resilience4j/common/retry/configuration/RetryConfigurationProperties.java#L362-L370

Your answer work for me. Thank you.
