### ISSUE TITLE
Support failure rate threshold < 1?

### ISSUE THREAD

**Issue by kai33** [resilience4j/resilience4j#139]
Hi Resilience4j team,

I was trying the library, it's great and provides exactly what I need.
Just that in the circuit breaker config, it has a limit that `failureRateThreshold must be between 1 and 100`.

May I know is there any historical reason that it can't be < 1 (still > 0)?
Because I have a use case which is really sensitive to the failure rate (like 0.05%)

**Comment by RobWin** [comment]
Hi @kai33 
Thx for evaluating Resilience4j. If you like it, we would love to get your GitHub star :)
Indeed, we never thought that someone would need such a sensitive failure rate. How did you configure your `ringBufferSizeInClosedState`? You need a size of 2000 so that 0.05% makes sense. 1 failed call out of 2000 would change the CircuitBreaker state to OPEN.

We could change that in the next release.

**Comment by kai33** [comment]
Thank you! starred :+1: 
Yes it'll require a larger ringbuffer size
