### ISSUE TITLE
CircuitBreakerConfigurationProperties has no ignoreException property

### ISSUE THREAD

**Issue by LeoNiedermeier** [resilience4j/resilience4j#1586]
Resilience4j version: 1.7

Java version: any

The documentation of CircuitBreaker (https://resilience4j.readme.io/docs/circuitbreaker) describes a property "ignoreException" ("A custom Predicate which evaluates if an exception..." , not to confuse with the property "ignoreExceptions"). But configuring a ignoreException in a spring boot application has no effect.
It seems, that "ignoreException" is not present in CircuitBreakerConfigurationProperties (https://github.com/resilience4j/resilience4j/blob/master/resilience4j-framework-common/src/main/java/io/github/resilience4j/common/circuitbreaker/configuration/CircuitBreakerConfigurationProperties.java).

Note:
The similar retry-property "retryExceptionPredicate" works like expected.

**Comment by RobWin** [comment]
Yes, unfortunately it was called differently in our Spring Boot 2 module.

`recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate`

**Comment by RobWin** [comment]
Yes, indeed.
Would you like to create a PR?

We only have a `recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate`.
But you cannot use it to ignore exceptions, but only count them either as a failure or success :(

**Comment by shubham2705** [comment]
Hi, Any update when we can have the ignoreExceptionPredicate for spring boot available. Currently, I am passing the predicate by creating custom CircuitBreakerConfig and setting in ignoreException. I would love to have this thing controlled from external configuration. as I have defined all the configurations in my application.yml

**Comment by shubham2705** [comment]
Also, let me know if I can contribute to this somehow

**Comment by SirGian99** [comment]
Hi, since I have the same issue I was digging a bit trying to understand how to possibly solve it. I noticed, as shown here, that the issue was solved by @melochin  in commit [063f9c2](https://github.com/resilience4j/resilience4j/commit/063f9c2e429d6f2a8aa88e6f20422207bc98db34). 
However, the method "buildConfig" that was modified in class io.github.resilience4j.common.circuitbreaker.configuration.CircuitBreakerConfigurationProperties is now marked as deprecated. Is it possible to somehow port this change to the new logic that is used to build the config starting from the external configuration in application.yml? I would do it myself but I can't find where the actual code that reads the configuration is.

**Comment by RobWin** [comment]
Any PR is welcome

**Comment by StokleyO** [comment]
Was this ever solved?

**Comment by RobWin** [comment]
No

**Comment by matteoroxis** [comment]
> No

Is there a roadmap for the resolution?

**Comment by RobWin** [comment]
No, we need contributions from the community.
I'm too busy at work and family unfortunately :(

**Comment by melochin** [comment]
Resolved since relese 2.0.0. Test it with latest version, it works fine. ``ignoreExceptionPredicate`` property can be used in spring boot configuration file.

**Comment by melochin** [comment]
Resolved since release 2.0.0. Test it with latest version, it works fine. ``ignoreExceptionPredicate`` property can be used in spring boot configuration file.
