### ISSUE TITLE
New module that collects overall information

### ISSUE THREAD

**Issue by mkopylec** [resilience4j/resilience4j#1625]
Resilience4j version: newest

Java version: doesn't matter

Hi.
What do you think about adding a new module, let's say `resilience4j-status`, which will collect overall metrics (maybe more things like logs or something) for each operation it decorates?
By overall metrics I mean:
counters:
```
resilience4j.status.operation-1.successes
resilience4j.status.operation-1.exceptions
resilience4j.status.operation-1.exceptions.java-lang-exception (exception class name)
```
timers:
```
resilience4j.status.operation-1.duration
```

**Comment by madhava-sridhar** [comment]
there's micrometer module that already exposes these metrics 
https://resilience4j.readme.io/docs/micrometer, is this requirement quite different from what "resilience4j-micrometer" already does ?

**Comment by RobWin** [comment]
Hi,
I think the difference is that the metrics are per circuitbreaker instance or retry instance.
He would like to have a metric per decorated "method", correct?

**Comment by mkopylec** [comment]
Yes, exactly @RobWin

**Comment by mkopylec** [comment]
Maybe the new decorator could be implemented inside resilience4j-micrometer module.

**Comment by madhava-sridhar** [comment]
thanks @RobWin and @mkopylec , this weekend i will give  a try with building decorator for resilience4j-micrometer module.

**Comment by mkopylec** [comment]
@madhava-sridhar Any update on this? :)

**Comment by mkopylec** [comment]
@RobWin I've added a PR for that. Please check it out.

**Comment by RobWin** [comment]
Hi,

I think I would not mix metrics and logging in a single decorator. For logging we can make use of event handlers.

I've implemented an Aspect in one of my projects  which combined a several metrics (Meter and Timer) into a single annotation which could be attached to any public method or class. It measured the execution rates, success/error counts and execution time of methods.
The Aspect added the class name and method name dynamically as tags to the metrics so that I was able to filter in Grafana or Prometheus.
That way I was able to see which methods or classes are the slowest or the methods which are called the most often.

I think that could be a nice addition. Unfortunately I don't have access to the code anymore. 

Would someone be interested to implement this?

**Comment by mkopylec** [comment]
Hi, IMO it should be implemented as a raw API like any other decorators. It could be an aspect in spring boot module like there is for any other decorators. The reason is that it would be nice to have a possibility to combine the new module with others using resilience4j-all. Also aspects force you to have a public method that wraps the decorated function. You don't have this limitation by using in-code API. Also not everyone uses Spring. Setting up AOP without a framework that supports it can be difficult.
As for the module itself. The PR is just a draft. I can implement it (and name it) however you like.
>For logging we can make use of event handlers.
Events are published while using decorators. What if someone would like to just use the logging feature, without any decorator?

I'm also struggled how to implement metrics. In the PR I did it analogically to other decoratos, but in other decorators metrics are just additional feature. In the introduced module metrics are the core feature, thus maybe they shouldn't relay on event handlers.

**Comment by mkopylec** [comment]
Any feedback here? How would you like to implement these features?

**Comment by RobWin** [comment]
Hi, I still like the idea, but I prefer to separate measuring metrics from logging.

I once introduced a Timer decorator for Dropwizard metrics, but never migrated it to Micrometer.

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-metrics/src/main/java/io/github/resilience4j/metrics/Timer.java

Maybe you are interesting in creating something comparable for Micrometer. 
We also once had an idea to implement a Tracing decorator. See: https://github.com/resilience4j/resilience4j/issues/27
A logging decorator which logs whenver a method is entered, successful or failed would also be nice. But I really see it as a separate decortor so that users can choose more fine granular what they need.

**Comment by RobWin** [comment]
I think we could move it into a dedicated module, maybe something like resilience4j-sl4j-logging ?

**Comment by mkopylec** [comment]
I created a draft for metrics feature. Please check it out. If it is OK for you I'll add unit tests, spring support, kotlin support etc.

**Comment by mkopylec** [comment]
> I think we could move it into a dedicated module, maybe something like resilience4j-sl4j-logging ?

Sounds good, will add the new module after finishing the metrics feature.

**Comment by mkopylec** [comment]
I'm wondering what order should be set for the Timer aspect. Currently we have:
`Retry ( CircuitBreaker ( RateLimiter ( TimeLimiter ( Bulkhead ( Function ) ) ) ) )`
If we set it like this:
`Retry ( CircuitBreaker ( RateLimiter ( TimeLimiter ( Bulkhead ( **Timer** ( Function )  ) ) ) ) )`
there will be no metrics if any of the previous aspects fail.
If we set it like this:
`**Timer** ( Retry ( CircuitBreaker ( RateLimiter ( TimeLimiter ( Bulkhead ( Function ) ) ) ) ) )`
the rate metrics won't count retries, and the duration metric will sum up all retries durations.

What's your recommendation?

**Comment by RobWin** [comment]
Good question. 
Usually I would like to know if a call takes 5s, even if there is a 2s timeout configured.
Also with a ThreadPoolBulkhead. Do you want to know how long it takes until a thread takes over a task, or do you only want to know how long the task itself takes.
I guess it really depends on your usecase. 
Most simple solution would be: `Retry ( CircuitBreaker ( RateLimiter ( TimeLimiter ( Bulkhead ( **Timer** ( Function )  ) ) ) ) )`

**Comment by RobWin** [comment]
Hi, splitting into multiple PRs is fine

**Comment by mkopylec** [comment]
Can we move forward with this?
I've already have prepared the reactive support for the Timer.

**Comment by RobWin** [comment]
I can merge your MR. Could you just change onNoResult to onSuccess?

**Comment by mkopylec** [comment]
Done.

**Comment by mkopylec** [comment]
The above is the last PR as it comes to Timer.
Next PRs will implement the SLF4J logging decorator.
