### ISSUE TITLE
Add accessors to exception lists 

### ISSUE THREAD

**Issue by AnthonyJM18** [resilience4j/resilience4j#1636]
### Proposed Change -  Make public accessors to the following
1.  CircuitBreakerConfig - IgnoreExceptions, RecordExceptions
2. RetryConfig - RetryExceptions, IgnoreExceptions

### Why
In order to make testing and verifying exception lists (Ignore exceptions, Record exceptions, e.t.c) easier, there should be getters for each list that will allow the user to return a list of all specified exceptions.

### Benefits
This would allow users to verify that the list they retrieved matches the list they expect.

Another benefit would be that users could run a templated test in order to loop through all exceptions to throw each one and test the expected result.

**Comment by RobWin** [comment]
Hi,

I would like to avoid adding `getters` for fields which should not be part of the public API.

The `recordExceptionPredicate` and `ignoreExceptionPredicate` are evaluated based on different input parameters like `ignoreExceptions`, `recordExceptions`. 
Clients should never use `getIgnoreExceptions` or `getRecordExceptions` directly, that's why I would like to avoid it to make them part of the public API.
