### ISSUE TITLE
Trying to migrate hystrix, HystrixRuntimeException question

### ISSUE THREAD

**Issue by johnharby** [resilience4j/resilience4j#1704]
Resilience4j version: 1.7.0

Java version: 11.0.9

I am trying to migrate our code from Hystrix to Resilience4j (we're using Spring Cloud too). The code has been using HystrixRuntimeException for methods with @HystrixCommand and doing this type of check:

public String buildHystrixError(HystrixRuntimeException e) {
       if (e.getFailureType() == FailureType.TIMEOUT) {
                 return "Timeout occurred";
       }
       else {
                 return "Circuit breaker open on error";
        }
}

Do you know how I can do this with the @CIrcuitBreaker annotation in Resilience4j?

**Comment by RobWin** [comment]
CircuitBreaker don't have timeout exceptions, but only `CallNotPermittedException`.
Only the TimeLimiter does have a `TimeoutException`.

What do you want to achieve?

**Comment by johnharby** [comment]
I am trying to migrate a large existing codebase. There are many usages of @HystrixCommand in the code. Apparently for cases where there is no fallback specified the HystrixRuntimeException can be caught and the type of failure of timeout or other can be determined which is going on in the code I posted previously. Trying to figure out how to accomplish this with Resilience4J.

**Comment by RobWin** [comment]
As described, Resilience4j CircuitBreaker either throw CallNotPermittedException or the original exception.
Do you also use `@TimeLimiter` and/or `@Bulkhead`?

**Comment by blitz-de** [comment]
hi @johnharby, I am also trying to do the same. Did you find an answer to your question?

**Comment by blitz-de** [comment]
@RobWin, in my case, I want to configure the Exceptions which come out of resilience4J and get a cause of that exception accordingly. In Hystrix it was possible to do that using HystrixRuntimeException. 

Example: ```
if ex.getCause() instanceof HystrixRuntimeException && (ex.getCause() instanceof TimeoutException
|| ex.getCause() instanceof RejectedExecutionException)) { return true; ... etc.
```

If we would use the TimeLimiter or Bulkhead, how would it possible reach to similar results using them?

**Comment by RobWin** [comment]
Can you provide me more context?
Resilience4j is not wrapping any exceptions. There should no need to get a cause of an exception.

**Comment by sakhrNab** [comment]
Hi Robin, 

The reason behind is when we have services provided from a 3rd party, where we can't handle the implementation of their services and if they are not reachable (they might not have any circuit breaker implemented), making our implemented service unreachable, without knowing the cause. Therefore, in Hystrix, when we had such a case, we disabled the fallbackMethod using "withFallbackEnabled(false)" and threw exceptions accordingly using the "HystrixRuntimeException". HstrixRuntimeException is thrown when a HystrixCommand fails and does not have a fallback, making us know the reason behind the cause of the exception. 

This is why, we were searching for something similiar in Resilience4j, because it is an important functionality when we're dependant from 3rd party services.

**Comment by RobWin** [comment]
Can you show me how you have implemented so far?
I don't understand the isse. In Resilience4j you don't have to throw any custom exceptions.

**Comment by sakhrNab** [comment]
an example which I found online and is quite similiar to our impl can be found here:
[HystrixException Example](https://www.tabnine.com/code/java/classes/com.netflix.hystrix.exception.HystrixRuntimeException) 

Another use cases to have a better overview: 
* handling of hystrix failures. When something wrong happens with Hystrix or Hystrix-Command-Wrapper, we could render an exception to the user using the our site. 
* If a fallbackMethod is not working and we want to catch the Exception from the log also and again render it to the user. 

Here is also a link of how HystrixRuntimeException is supposed to work [HystrixRunTimeExceptions](https://netflix.github.io/Hystrix/javadoc/com/netflix/hystrix/exception/HystrixRuntimeException.html)

I hope it is somehow clearer now.

**Comment by RobWin** [comment]
I don't want to see a Hystrix Example :)
I would like to see what you have done so far?
I guess you are asking questions AFTER looking at the Resilience4j example and playing around with it?

**Comment by sakhrNab** [comment]
Hi @RobWin, Unfortunately, we haven't integrated Resilience4J on the current project. I just have general experience with it, using other features. 

Now, we are thinking to migrate our project from Netflix to Resilience4J and we've some use cases we need, like the one above. We are however, still sceptical about starting the migration and in the middle of it all, that some of the cases we need isn't available in Resilience4J. 

We are using Spring Boot, and thinking of using Resilience4J annotations. We might also need to combine the Circuit-Breaker, with bulkhead and rate limiter to fullfil some of the previous requirements.

**Comment by RobWin** [comment]
Yes, in order to replace Hystrix you need to combine Bulkhead (Semaphore or Threadpool), TimeLimiter and CircuitBreaker.
You can have a look at https://github.com/resilience4j/resilience4j-spring-boot2-demo/blob/master/src/main/java/io/github/robwin/service/BackendAService.java

The CircuitBreaker either throws `CallNotPermittedException`, if the CircuitBreaker is Open/Half-Open.
The TimeLimiter throws a `TimeoutException`.
The Bulkhead throws a `BulkheadFullException`.

You can catch them instead of `HystrixRuntimeException` or `RejectedExecutionException`.

**Comment by sakhrNab** [comment]
Thanks for your patiences and for walking me through this. I am going to check out the Exceptions above. 

Have a nice day to go.

**Comment by rcbandit111** [comment]
@RobWin I have this code:

```
public void handleHystrixException(HystrixRuntimeException hystrixException) {

    if (HystrixRuntimeException.FailureType.TIMEOUT == hystrixException.getFailureType()) {
      return new TimeoutException();
    }
}
```

What should be the proper way to migrate this code in CircuitBreaker?
