### ISSUE TITLE
Java 9 Modules Support

### ISSUE THREAD

**Issue by RobWin** [resilience4j/resilience4j#179]

**Comment by srinivasa1225** [comment]
@RobWin : Trying to include resilience4j with springboot2 but getting the bean error .java.lang.NoClassDefFoundError: org/springframework/boot/actuate/endpoint/AbstractEndpoint..This is the error i am getting

**Comment by srinivasa1225** [comment]
Can you please help me in resolving the issue

**Comment by srinivasa1225** [comment]
Yes..but using some old version of spring boot.now the issue has been
resolved.Thanks for ur quick reply.

**Comment by jarpz** [comment]
@RobWin do you know when version 0.13.0 is going to release?

**Comment by RobWin** [comment]
Because of spring boot 2 or java9 support?

**Comment by srinivasa1225** [comment]
When can we expect the resilience4j 0.13 release

On Apr 21, 2018 7:08 AM, "Robert Winkler" <notifications@github.com> wrote:

Because of spring boot 2 or java9 support?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/resilience4j/resilience4j/issues/179#issuecomment-383223009>,
or mute the thread

**Comment by RobWin** [comment]
There is a Spring Boot2 module

**Comment by squarepegg** [comment]
> There is a Spring Boot2 module

Ahh, thanks. I was looking at the demo which is tied to Spring Boot 1.
