### ISSUE TITLE
java.lang.ClassNotFoundException: io.vavr.CheckedFunction0

### ISSUE THREAD

**Issue by ek-ex** [resilience4j/resilience4j#1934]
Resilience4j version:
2.0.2
Java version:
17
Springboot version 
3.0.5

When using the latest version of resilience4j-retry, its failing to start the application with the error 
```stackTrace="java.lang.ClassNotFoundException: io.vavr.CheckedFunction0```

I understand that vavr dependency was removed in 2.0.2 but then why does it requires it? Shouldnt it be optional? 

Thanks

**Comment by RobWin** [comment]
Do you have a longer stacktrace? It should show where the class is still needed?

**Comment by smurf667** [comment]
For what it's worth here is some additional information for other people potentially battling with this: We saw this problem too - as it turns out we were providing a library that implemented `CircuitBreaker` as an interceptor. We [compiled with 1.7.1](https://github.com/resilience4j/resilience4j/blob/1.7/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/CircuitBreaker.java) and then tried to use with 2.0.2. This caused a `NoClassDefFoundError`. So, this is a backwards-compatibility issue that only occurs when mixing 1.x and 2.x (obviously not a good idea).

**Comment by RobWin** [comment]
In resilience4j 2.0.2 you need to add [resilience4j-vavr](https://github.com/resilience4j/resilience4j/tree/master/resilience4j-vavr) and perform some code changes.
