### ISSUE TITLE
How to configure for metrics in grafana or new relic

### ISSUE THREAD

**Issue by jpdev01** [resilience4j/resilience4j#1950]
Resilience4j version: 1.7.0

Java version: 1.8.0

I would like to configure the metrics to go to Grafana, but I would not like to configure Prometheus in the cloud. Is it possible to configure without?

**Comment by RobWin** [comment]
Sure,
Just check look up the documentation of Micrometer and use something else which Grafana supports.
https://micrometer.io/docs

This has nothing to do with Resilience4j, since we are using Micrometer internally and you can configure any other monitoring system than Prometheus which is supported by Micrometer
