### ISSUE TITLE
CircuitBreaker Inconsistency

### ISSUE THREAD

**Issue by yannxia** [resilience4j/resilience4j#290]
first to trigger CircuitBreaker OPEN，must full of ringBufferSizeInClosedState， but next unnecessary。

**Comment by yannxia** [comment]
@RobWin  not AutomaticTransitionFromOpenToHalfOpen.

when you first time trigger CircuitBreaker be `OPEN`， you must wait `ringBufferSizeInClosedState` times error, for example:  

```bash
maxFailureThreshold = 50
ringBufferSizeInClosedState = 30
```

call some `error` url,  all call will fail, but when you fail `16th` calls, it's  CircuitBreaker still `CLOSE`, must be full of `ringBufferSizeInClosedState` , when `31th` calls, it's CircuitBreaker will be 'OPEN'。

----

but  wait it recover from `Half_OPEN` to  `CLOSE`， when you fail `16th` calls, CircuitBreaker will be 'OPEN'.

----

```java
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("test", CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("test", CircuitBreakerConfig.custom()
    .waitDurationInOpenState(Duration.ofSeconds(1))
    .failureRateThreshold(50.0f)
    .ringBufferSizeInHalfOpenState(10)
    .ringBufferSizeInClosedState(20)
    .build());


for (int i = 0; i < 19; i++) {
    circuitBreaker.onError(0, new RuntimeException());
}

Assert.assertEquals(circuitBreaker.getState(), CircuitBreaker.State.CLOSED);

circuitBreaker.onError(0, new RuntimeException());
Assert.assertEquals(circuitBreaker.getState(), CircuitBreaker.State.OPEN);  //21th call, why not is 11th?
```

```xml
version:  resilience4j: 0.13.1
```

**Comment by RobWin** [comment]
Yes it is fails / ring size if the ring buffer is full

**Comment by RobWin** [comment]
If you are interested, please have a look at https://github.com/resilience4j/resilience4j/blob/master/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/RingBitSet.java

**Comment by raghanag** [comment]
Hi @RobWin We are planning to use the library to wrap our external system calls with circuit breaker, currently, the config of the circuit breaker does not have the fallback method. And also could you please explain to me why do we need to decorate the service method instead of directly executing the supplier by using the executeSupplier. And is it always good practice to use the registry or is it okay to create the CB instances directly, currently, we process about 20K request per hour per JVM instance. Could you please recommend the best practices. Thanks, Naga.

**Comment by RobWin** [comment]
Hi,
why did you add the question to this closed issue?

You don't have to necessarily decorate your service method. You can always just use `

`Result result = circuitBreaker.executeSupplier(() -> service.method(param));`

But when you decorate your service method, it allows you to add another decorator like `Retry`. If your service method fails, it will be automatically retried.
If you use `resilience4j-all`, you can just do:

```
Supplier<Result> decoratedSupplier = Decorators.ofSupplier(() -> servoce.method())
                .withCircuitBreaker(CircuitBreaker.ofDefaults("helloBackend"))
                .withRetry(Retry.ofDefaults("id"))
                .decorate();
Result result = decoratedSupplier.get();
```

I would suggest you to use the registry, because normally you want to use the same CB instance to protect multiple service methods. If you inject the registry, you can always get the same instance.

`CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("backendName");`

Some features like MicroMeter metrics only work if you use the registry. 

```
MeterRegistry meterRegistry = new SimpleMeterRegistry();
TaggedBulkheadMetrics.ofBulkheadRegistry(circuitBreakerRegistry).bindTo(meterRegistry);
```

And you can globally attach event consumers to CircuitBreaker instances as follows:

```
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
    circuitBreakerRegistry.getEventPublisher()
        .onEntryAdded(entryAddedEvent -> {
            CircuitBreaker addedCircuitBreaker =  entryAddedEvent.getAddedEntry();
            LOG.info("CircuitBreaker {} added", addedCircuitBreaker.getName());
            addedCircuitBreaker.getEventPublisher().onEvent(circuitBreakerEvent -> LOG.info(circuitBreakerEvent.toString()));
        })
        .onEntryRemoved(entryRemovedEvent -> {
            CircuitBreaker removedCircuitBreaker =  entryRemovedEvent.getRemovedEntry();
            LOG.info("CircuitBreaker {} removed", removedCircuitBreaker.getName());
        });
```

**Comment by RobWin** [comment]
Btw, if you use Spring Boot 2. Everything is much simpler.
