### ISSUE TITLE
RxJava 2.2.4 broke operator implementations

### ISSUE THREAD

**Issue by sfitts** [resilience4j/resilience4j#301]
Release [2.2.4](https://github.com/ReactiveX/RxJava/releases/tag/v2.2.4) of RxJava removed `SubscriptionHelper.isCancelled` which is currently used by the operator implementations.  Honestly I'm tempted to log this as an RxJava bug since this kind of breaking change in a patch release is unfriendly.  However, the class in question is internal, so...

Anyway, until this is fixed moving beyond 2.2.3 will be impossible.

**Comment by danielimre** [comment]
While making `BulkheadSubscriber`, `CircuitBreakerSubscriber` and `RateLimiterSubscriber` work both with former and latest RxJava is simple, I found that 2.2.4 also broke `RetryTransformer` which needs to be redesigned if we want to support both versions of RxJava. The problem is with `SubscriptionArbiter` as its constructor has changed.
Looking at the implementation of e.g. `Observable#retry` and `RetryTransformer`, they are pretty close to each other. I assume `RetryTransformer` was originated from RxJava code directly. The question is whether we want to do the same again as it would still require internal classes to be used. (I haven't checked if it can be done in a backward-forward compatible way at all.) It would be good to avoid similar issues in the future. 
@RobWin what's your thought on this?

**Comment by Romeh** [comment]
@danielimre  i guess this will be covered by https://github.com/resilience4j/resilience4j/pull/356

**Comment by Romeh** [comment]
@sniff 0.14.0 is released , can u please test it out again ?
