### ISSUE TITLE
[spring-boot] CircuitBreakerAutoConfiguration is called after Health endpoint configuration

### ISSUE THREAD

**Issue by bjab** [resilience4j/resilience4j#368]
Issue is, that `EndpointAutoConfiguration` is called before `CircuitBreakerAutoConfiguration`, so `healthIndicators` does know nothing about circuit breakers health indicators.
I had to define dependency myself (see https://stackoverflow.com/a/31708034/344141):

```
@Configuration
public class ResilienceDependsOnBeanFactoryPostProcessor implements BeanFactoryPostProcessor {

    @Override
    public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
        String[] beanNames = BeanFactoryUtils.beanNamesForTypeIncludingAncestors(
            beanFactory, EndpointAutoConfiguration.class, true, false);
        Arrays.stream(beanNames)
            .map(beanFactory::getBeanDefinition)
            .forEach(definition -> definition.setDependsOn(
                StringUtils.addStringToArray(
                    definition.getDependsOn(),
                    CircuitBreakerAutoConfiguration.class.getCanonicalName()
                ))
            );
    }
} 
```

Spring boot 1.5
resilience4j 0.13.2

_Originally posted by @bjab in https://github.com/resilience4j/resilience4j/issues/295#issuecomment-475163664_

**Comment by RobWin** [comment]
Hi thx.
Thanks strange, because it works with Spring Boot 2. There is a test which verifies it.

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring-boot2/src/test/java/io/github/resilience4j/circuitbreaker/CircuitBreakerAutoConfigurationTest.java#L105

But indeed a Spring Boot 1 test is missing:

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring-boot/src/test/java/io/github/resilience4j/circuitbreaker/CircuitBreakerAutoConfigurationTest.java

**Comment by RobWin** [comment]
I think we have to add a `@AutoConfigureBefore(EndpointAutoConfiguration .class)` to `CircuitBreakerAutoConfiguration`.
Woud you like to create a PR and a test?

**Comment by RobWin** [comment]
Would you like to test the 0.14.0-SNAPSHOT version to check if your issue is fixed?

**Comment by RobWin** [comment]
0.14.0 was released
