### ISSUE TITLE
OSGI support

### ISSUE THREAD

**Issue by david-t-daniel** [resilience4j/resilience4j#47]
It would be great if osgi support was able to be added.  There is a bndtools gradle plugin that may be able to add the correct exports https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md#gradle-plugin-for-workspace-builds

**Comment by RobWin** [comment]
Hi,
good idea. If you have experience wit this plugin, would you like to create a PR and add this?

**Comment by david-t-daniel** [comment]
I will give it a try but it may take a couple weeks since I have never used Gradle and have lots to do now. Still it is probably not a pressing issue as I am the first to ask for it. Thank you

**Comment by RobWin** [comment]
Thx, no hurry :)

**Comment by cpilsworth** [comment]
Created a PR with some very basic changes to add OSGi manifest headers. Just need to know if the some dependencies can be considered _optional_... see #56

**Comment by cpilsworth** [comment]
@david-t-daniel take a look at the linked PR for this issue and see if it does what you need.

**Comment by david-t-daniel** [comment]
I will do that this weekend.  Thank you very much for putting in the effort on this.

**Comment by markusheer** [comment]
Hi

I tried to use Resilience4j in Apache Felix (Adobe Experience Manager). Activation of the bundles works but during runtime there is a class loading issue in io.github.resilience4j.circuitbreaker because the io.github.resilience4j.core package is not defined in Import-Package.

This is because in publishing.gradle the io.github.resilience4j package is excluded in the Import-Package section.

A solution is to change the exclude to to current projects package:
`instruction 'Import-Package', "!${project.osgiManifest().symbolicName}.*,*"`

**Comment by RobWin** [comment]
Thx. Fixed it.
Could you please test `0.11.1-SNAPSHOT` when the build is complete.

**Comment by markusheer** [comment]
That was fast. Tested via local build from master and it works.

**Comment by RobWin** [comment]
Thx 👍

**Comment by storozhukBM** [comment]
@RobWin should we make 0.11.1 release or wait for 0.12.0 ?
