### ISSUE TITLE
Circuit Breaker buffer time interval handling

### ISSUE THREAD

**Issue by codingL3gend** [resilience4j/resilience4j#547]
is there any way to implement a time interval that the circuit breaker could use to evaluate request through the breaker over that interval to determine the failure rate threshold against as well. currently with this being a difference in resilience4j in comparison to Hystrix if the buffer size in the closed state was a value of 100 and say only 60 request came through the breaker in 5 mins and 30 failed and 30 succeeded the breaker would not calculate the failure rate until it reaches the 100. this is problematic because if some time later 40 more request came through the system  and the breaker still had history of the request and then 20 failed and then 20 succeeded at this time the breaker would move to an open state even though the backend system may not be experiencing issues. resetting the breaker does not solve this problem since the metrics would be lost and forcing the breaker to change state based on a calculation of the failure rate manually is not ideal either. is there an elegant way of handling such a situation?

**Comment by RobWin** [comment]
Hu, thank you for your question.
I think there are 3 options

1) You could reduce the ring buffer size to a lower value so that the failure rate is calculated faster/earlier.

2) We implement a different CircuitBreaker strategy which uses a sliding time window.

3) We implement a different CircuitBreaker strategy which uses a weighted mean where older values contribute less.

**Comment by RobWin** [comment]
4 option is of course that you keep Hystrix

**Comment by codingL3gend** [comment]
@RobWin thanks for the reply, to your points mentioned we considered option 1 which is only slightly viable because it essentially will yield the same results. simply having the breaker setup to fail faster doesn't entirely address the issue since the tuning will have to be just right so that there are no preemptive moments of the breaker opening simply due to minor blips. of course with enough test and tuning that approach could perhaps get to an ideal configuration but the issue still remains that the breaker still will maintain state of request over time and could cause issues if the throughput over time wasn't that great. option 2 would be great, that is an approach that we utilize with the Polly framework for .net and it is more efficient. option 3 is also a great idea since it would help to get rid of outliers much more efficiently. option 4 is viable but we haven't done an implementation with Hystrix because research pointed to resilience4j as being better. i like resilience4j as a framework; it's just this one hick up.

**Comment by RobWin** [comment]
@codingL3gend Please be aware that you still need to tune a CircuitBreaker that uses a sliding time window implementation.
Polly as well as Hystrix require you to configure `minimumThroughput` or `requestVolumeThreshold` according to the request rate of your system. Otherwise the CircuitBreaker will not trip open even if all calls failed.
On the other side, the current CircuitBreaker implementation of Resilience4j does not ignore any request that failed, even if the request rate is low. The RingBuffer-based implementation has advantages and also disadvantages. A weighted RingBuffer implementation might be the best solution.

**Comment by codingL3gend** [comment]
I am aware of the tuning needed for Polly and Hystrix of course. The
minimum throughput combined with the sampling duration for Polly imo allows
for better tracking of failures and successes because it more efficiently
monitors if the system is really broken or if it perhaps was only
performing badly momentarily. The resilienc4j approach isn't bad it's just
the history of the failures that can take some looking into because that
history will be kept no matter what even if request came in and then an
entire day passed with no request to the system and then more request come
in. With that history being stored it would cause the breaker to trip if it
were already close to the failure threshold from the previous day and then
a few failures came in the next day to push it over. Outrageous scenario I
know but one that can happen. We also saw this scenario during a
performance test with huh load as well which promoted me to investigate the
issue and how the breaker was really working.

**Comment by RobWin** [comment]
Ok, you convinced me :)
I will implement a Sliding Time Window strategy.

**Comment by codingL3gend** [comment]
@RobWin That's great news :-D. what occurred during our load test was the following: we were sending through above normal load and around a time when one of our backend services tends to peak in response times and produce failures in the breaker it was observed that the circuit breaker was handling these scenarios correctly. the backend systems peak would level out and then the circuit breaker while in the half open state was appropriately re-evaluating request to determine if it needed to open again. so during one test the buffer size was 25 for the half open state with a 50% failure threshold and it marked 20 good and 5 bad so it moved back to a closed state; however it still kept a history of buffered calls and when it transitioned back to a closed state it was already at 5 failed and 20 successful calls that went through the buffer instead of refreshing all the stats (this could be how it was intended to work). now as more request came in for the breaker to approach the buffer size of 100 for the closed state the breaker was still evaluating request against the totals it already had. eventually it pushed out the failed request as expected and all things were good. however when the next peak moment happened the same occurred again but yet this time the failure threshold was almost reached but it transitioned back to the closed state and began servicing request again. now over perhaps the next 10 mins or so blips were happening were request would come in increasing the failed count and also the successful count but we saw it preemptively cause the breaker to open when a few request came in that had high response times even though the backend system wasn't performing badly because it held onto the bad request for more than a 5 minute or so window. this caused the breaker to continuously go from half open to open for about 5-10 minutes (this was in one scenario). Another scenario was similar but we saw some failures say about 40 and then 60 successful to reach the 100 buffer size and then some went successful and then more failures came in to cause the breaker to open but the backend system was performing badly but it was the history that was still stored for failures that should have been outliers by this time that caused it to still move to an open state. hopefully this makes sense

**Comment by RobWin** [comment]
First draft of a Sliding Time Window metric store is done.

The implementation backed by a sliding time window that aggregates only the calls made in the last N seconds.
The sliding time window is implemented with a circular array of N buckets.
If the time window size is 10 seconds, the circular array has always 10 buckets. Every bucket
stores the outcome of all calls which happen in a certain epoch second. The head bucket of the circular array stores the call outcomes of the
current epoch second. The other buckets stored the call outcomes of the previous {@code N-1} epoch seconds.

The sliding window does not store call outcomes (tuples) individually, but incrementally updates partial aggregations (bucket) and a total aggregation.
The total aggregation is updated incrementally when a new call outcome is recorded. When the oldest bucket is evicted, the partial aggregation of that bucket
is subtracted from the total aggregation and the bucket is reset. (Subtract-on-Evict)

The time to retrieve a Snapshot is constant 0(1), since the Snapshot is pre-aggregated and is independent of the time window size.
The space requirement (memory consumption) of this implementation should be nearly constant O(n), since the call outcomes (tuples) are not stored individually.
Only N partial aggregations and 1 total aggregation are created.

**Comment by RobWin** [comment]
The upcoming version of the CircuitBreaker will allow you to configure two different types of sliding windows. Either COUNT_BASED which records the last N calls or TIME_BASED which records the calls of the last N seconds.

The following configuration would be similar to the old ringbuffer-based implementation:
slidingWindowType = TIME_BASED
slidingWindowSize = 100
minimumNumberOfCalls = 100

The following configuration would be comparable to Hystrix:
slidingWindowType = TIME_BASED
slidingWindowSize = 10 -> which is 10 seconds
minimumNumberOfCalls = 20 -> which means is comparable to [requestVolumeThreshold](https://github.com/Netflix/Hystrix/wiki/Configuration#circuitBreaker.requestVolumeThreshold)

COUNT_BASED in code:
```
CircuitBreakerConfig.custom()
    .slidingWindowInClosedState(100, 100, SlidingWindow.COUNT_BASED)
    .build().
```

or 

TIME_BASED in code:
```
CircuitBreakerConfig.custom()
    .slidingWindowInClosedState(10, 20, SlidingWindow.TIME_BASED)
    .build().
```

**Comment by codingL3gend** [comment]
@RobWin  thanks for this update. sorry it took me some time to respond to this thread. how often does the bucket drop request or update itself when no more calls are being executed through the breaker? such as if the array bucket size is full for the sliding window time i.e 10, and then no more request execute through the breaker for it to drop/kick n-1 request from the breaker; when will it adjust itself on it's own? is there logic based on the current epoch time that will handle that automatically?

**Comment by RobWin** [comment]
SlidingTimeWindow: Whenever a call is recorded or a metrics snapshot is retrieved (via `metrics.getSnapshot()`) the outdated 
buckets are evicted.

**Comment by codingL3gend** [comment]
ok i will try to get this tested out to see how it performs. i'm hopeful that it will work out.

**Comment by RobWin** [comment]
The change is backward compatible. The sliding window type is by default COUNT_BASED. The `CircuitBreakerConfig.Builder` still has the method `ringBufferSizeInClosedState`.
The method configures `minimumNumberOfCalls` and `windowSize` for you so that it is backward compatible.
`minimumNumberOfCalls` is required now, because a time-based sliding window must know after how many recorded calls the failure rate should be calculated. You can use `minimumNumberOfCalls` also for a count-based sliding window in order to start calculating the failure rate after 10 calls, even if the ring buffer size is 100.

**Comment by RobWin** [comment]
The documentation https://resilience4j.readme.io will be updated as soon as 1.0.0 is released.

**Comment by RobWin** [comment]
>Another question is that, is there any way don't to record the rate of slow call? Sometimes we already had timeout settings in http connection, so we don't need it.
After this change, I may need to configure the slow SLOW_CALL_DURATION_THRESHOLD to a big one to avoid trigger it. It there any way to disable it?

No, there is no way to disable it, but the default value is 60s which is quite long. And the slow call rate threshold is 100% which means the CircuitBreaker opens only when all recorded calls took longer than 60s.

**Comment by wl1244hotmai** [comment]
This seems a huge change that totally change the concept of ringbuffer described in guides. (https://resilience4j.readme.io). What should we do to migrate to 1.0.0 version from 0.17.0 or older one?

Also, why we need 2 parameters: minimumNumberOfCalls and SlidingWindowSize in COUNT_BASED mode. acutally these two are ringbufferSize before. It looks a little confusing.

Another question is that, is there any way don't to record the rate of slow call? Sometimes we already had timeout settings in http connection, so we don't need it.
After this change, I may need to configure the slow SLOW_CALL_DURATION_THRESHOLD to a big one to avoid trigger it. It there any way to disable it?

**Comment by RobWin** [comment]
See answers above ;)

**Comment by wl1244hotmai** [comment]
Ye, I saw it, thx.
So, 
1. What's the difference between minimumNumberOfCalls  and windowsSize in COUNT_BASED mode? minimumNumberOfCalls = 10, windowsSize =100. then the circuit breaker may open when there are 10 calls, I don't understand why 100 will be used.
2. I see ringBufferSizeInClosedState still there, but deprecated, will we remote it in future? What's the suggested way to applay count mode? keep minimumNumberOfCalls and windowsSize same or different?

**Comment by RobWin** [comment]
Yes, `ringBufferSizeInClosedState` will be removed in the future. You should use `slidingWindowSize` and `minimumNumberOfCalls` instead.

When you use a count-based sliding window the `slidingWindowSize` controls the maximum number of calls which are included into the calculation of the failure rate. `slidingWindowSize` could be also called `maxNumberOfCalls`.

`minimumNumberOfCalls` instead controls the minimum number of calls required before the failure rate can be calculated. For example you don't want to wait until 100 calls are recorded, but you would prefer to calculcate the failure rate already after 10 calls.

**Comment by wl1244hotmai** [comment]
Thx RobWin, it helps a lot
