### ISSUE TITLE
circuitbreaker is called but have an issue

### ISSUE THREAD

**Issue by molakarajarao** [resilience4j/resilience4j#575]
Hi All,

I have configured circuitbreaker and fallback, when i have an 500 INTERNAL_SERVER_ERROR  circuitbreaker is called to fallback but i checked metrics there is no information OPEN status gets increased.

name="getshippinginfo",state="closed",} 1.0
resilience4j_circuitbreaker_state{application="ClassA",name="getshippinginfo",state="open",} 0.0
resilience4j_circuitbreaker_state{application="ClassA",name="getshippinginfo",state="forced_open",} 0.0
resilience4j_circuitbreaker_state{application="ClassA",name="getshippinginfo",state="half_open",} 0.0 

Here is my configuration example-----

```
@CircuitBreaker(name = "getshippinginfo")
public class ClassA {
// Success message or 500 error
public String success() throws Exception {
		if(serviceResponse.getStatusCode()==200 || serviceResponse.getResponseObject().getSuccess().equalsIgnoreCase("true")){
			return serviceResponse;
		}else {
			return fallback();
		}
// same method signature applied to fallback
@CircuitBreaker(name ="getshippinginfo", fallbackMethod = "fallback")
	public String fallback() {	
		serviceResponse.setStatusCode(HttpStatus.INTERNAL_SERVER_ERROR.value());
		serviceResponse.setErrorResponse(errorResponse);
		serviceResponse.setRequestObject(request);
		ServiceCircuitBreaker();
		return serviceResponse;
	}
	}
// CircuitBreaker configuration.
private io.github.resilience4j.circuitbreaker.CircuitBreaker ServiceCircuitBreaker() {
		CircuitBreakerConfig config = CircuitBreakerConfig.custom()
				.waitDurationInOpenState(Duration.ofMillis(1000))
				.ringBufferSizeInClosedState(10)
				.ringBufferSizeInHalfOpenState(2)
				.automaticTransitionFromOpenToHalfOpenEnabled(true)
				.failureRateThreshold(10)
				.build();
		return circuitBreakerRegistry.circuitBreaker("getshippinginfo", config);
	}

}
```

**Comment by RobWin** [comment]
Please use markdown to format your issues.

**Comment by molakarajarao** [comment]
I don't see CircuitBreaker OPEN status in metrics.The failed status 500 done morethan 50 times.

But the report shows is same as below.
name="getshippinginfo",state="closed",} 1.0
resilience4j_circuitbreaker_state{application="ClassA",name="getshippinginfo",state="open",} 0.0
resilience4j_circuitbreaker_state{application="ClassA",name="getshippinginfo",state="forced_open",} 0.0
resilience4j_circuitbreaker_state{application="ClassA",name="getshippinginfo",state="half_open",} 0.0

**Comment by RobWin** [comment]
Does your method throw any exception? I can't see it in your code snippet.

**Comment by molakarajarao** [comment]
Hi RobWin-
fallback() - method throws the INTERNAL_SERVER_ERROR 500 error.
// same method signature applied to fallback
@circuitbreaker(name ="getshippinginfo", fallbackMethod = "fallback")
public String fallback() {
serviceResponse.setStatusCode(HttpStatus.INTERNAL_SERVER_ERROR.value());
serviceResponse.setErrorResponse(errorResponse);
serviceResponse.setRequestObject(request);
ServiceCircuitBreaker();
return serviceResponse;
}
}

**Comment by RobWin** [comment]
Please format your  code snippets with markdown. https://guides.github.com/features/mastering-markdown/

Do you have an example project? It's difficult to understand what you are actually doing. Did you have a look at our Spring Boot2 demo?

**Comment by RobWin** [comment]
Please be aware that due to Spring AOP proxy based concept, you can't add an annotation to a method which is internally invoked my another method. For example the annotation of `fallback` doesn't work if you call the method inside of the `success` method.  The annotation only works if you invoke `fallback` from outside of the class.

**Comment by molakarajarao** [comment]
Hi RobWin - Here is my actual code, I took Spring Boot2 demo example and did similar way implemented in my class. i have to call "return fallback()"  inside success method because it throws 500 error there. please check below code and let me know your suggestions.

@Override
	public CoreServiceResponse<ShippingInfoRequest, ShippingInfoResponse> success() throws 
         Exception {
		long startTime = System.currentTimeMillis();
		serviceResponse=new CoreServiceResponse<>(getResponse());
		serviceResponse = shippingInfoDao.getShippingInfoExecutor(getRequest(), getResponse(),
				getSiteType(), getEnvironment(),getAuthorization());
		LOGGER.error("Total time taken in Service :: " + (System.currentTimeMillis() - startTime));
		if(serviceResponse.getStatusCode()==200 && serviceResponse.getHasErrorResponse().equalsIgnoreCase("false")  || serviceResponse.getResponseObject().getSuccess().equalsIgnoreCase("true")
		  ){
			return serviceResponse;
		}else {
			return fallback();
		}
	}

	@CircuitBreaker(name ="/getshippinginfo", fallbackMethod = "fallback")
	@Override
	public CoreServiceResponse<ShippingInfoRequest, ShippingInfoResponse> fallback() throws Exception {
		LOGGER.error("ShippingInfoInternalServiceGetApi Fallback invoked for {}", request);
		serviceResponse = new CoreServiceResponse<>();
		serviceResponse .setHasErrorRespoonse("true");
		CoreServiceErrorResponse errorResponse = new CoreServiceErrorResponse();
		errorResponse.setErrorMessage("ShippingInfoInternalServiceGetApi failed");
		serviceResponse.setStatusCode(HttpStatus.INTERNAL_SERVER_ERROR.value());
		serviceResponse.setErrorResponse(errorResponse);
		serviceResponse.setRequestObject(request);
		setCircuitBreakerRegistry(circuitBreakerRegistry);
		return serviceResponse;
	}

	@CircuitBreaker(name ="/getshippinginfo")
	private void setCircuitBreakerRegistry(CircuitBreakerRegistry circuitBreakerRegistry) {
		this.circuitBreakerRegistry = circuitBreakerRegistry;
		CircuitBreakerConfig config = CircuitBreakerConfig.custom()
				.waitDurationInOpenState(Duration.ofMillis(1000))
				.ringBufferSizeInClosedState(10)
				.ringBufferSizeInHalfOpenState(2)
				.automaticTransitionFromOpenToHalfOpenEnabled(true)
				.failureRateThreshold(10)
				.build();
		circuitBreakerRegistry.circuitBreaker("/getshippinginfo", config);
	}

**Comment by RobWin** [comment]
Hi,

I don't even know where to start. 
What is the purpose of your fallback method? A fallback method should never throw an exception or fail. A fallback method should recover an exception and return something useful to the client.

Besides that the method does not throw any exception, but returns a response with status code 500. The CircuitBreaker only counts exceptions as a failure.

Why do you invoke `setCircuitBreakerRegistry(circuitBreakerRegistry);` in your fallback? You don't need `setCircuitBreakerRegistry` at all. You can configure a CircuitBreaker via the Spring Boot properties file. Why do you have a `@CircuitBreaker` annotation around `setCircuitBreakerRegistry`.
I'm totally confused. Why do you have a `fallbackMethod="fallback"` around your `fallback` method? 

And again: Please be aware that due to Spring AOP proxy based concept, you can't add a @CircuitBreaker annotation to a method which is internally invoked my another method. For example the annotation of your `fallback` doesn't work if you call the method from you `success` method. The annotation only works if you invoke the `fallback` from outside of the class.
