### ISSUE TITLE
circuitBreaker - same threshold for errors and slow request in open or half-open mode

### ISSUE THREAD

**Issue by cless91** [resilience4j/resilience4j#667]
Hello, 

Is it possible to have a unique threshold counting errors and slow request in a same window ?

For example, given: 

- a slidingWindowType of type COUNT_BASED
- and a windows of size 4
- with failureRateThreshold configured to 50
- and slowCallRateThreshold configured to 50

When :
- i call my decorated function 10 times 
- and is has 1 slow call 
- and throws 1 error

Then :
- the state of the circuit breaker is still closed 
- and my decorated function was called 10 times

I would like to configure the circuit breaker so that in that scenario, it opens after the 4th call, effectively counting both slow calls and errors.

Is that possible ? If so how ? Is it an improvement ?
Thank you

**Comment by RobWin** [comment]
Hi,
no, its currently not possible. If you want to count slow calls as an error, I would recommend to configure a timeout on protocol level and record TimeoutExceptions as an error.
Is that possible for you?

Not sure if a successful slow call should be recorded as an error.

**Comment by cless91** [comment]
Hello, thank you for your answer

I'm just playing with the tool to understand and evaluate it, before using and suggesting it. 
So i don't have a "use case", per se.

I found a way around using a TimeLimiter, and yes configuring timeouts, for example http should be ok. And indeed in the metrics, the timeouts are counted as errors.

That would be nice to be able to configure the circuitBreaker to have a threshold for both though, not promising anything but if i happen to want to implement it, how is the process to contribute ?

I haven't contributed to anything yet. Do I just submit a pull request or should a get approval of some sort beforehand ?

**Comment by RobWin** [comment]
What do you mean by: "have a threshold for both though".
There is a threshold `slowCallRateThreshold` which you can decrease.

**Comment by cless91** [comment]
I'm french so maybe i am not very clear writing in english. What i mean by "have a threshold for both" going back to my toy case :

What would be nice to have is

given:

- a slidingWindowType of type COUNT_BASED
-  and a windows of size 4
- with some new parameter "errorAndSlowCallsRateThreshold" configured to 50

When :

- i call my decorated function 10 times
- and is has 1 slow call
- and throws 1 error

Then :

- the state of the circuit breaker is open
- and my decorated function was called 4 times

But, when :

- i call my decorated function 10 times
- and is has only 1 slow call or 1 error

Then :

- the state of the circuit breaker is closed
- and my decorated function was called 10 times

**Comment by RobWin** [comment]
I understand now what you mean. A flag like `recordSlowCallsAsError` might be a good idea.
But I think the flag is not really necessary in real life.
A system is usually either slowly decreasing performance because of overload or unavailable within a very short period of time. If the system is slowly decreasing performance and the response times are above the threshold but below a TimeoutException the CircuitBreaker opens. 
If the system is unavailable (IOExceptions) or too slow (TimeoutExceptions) within a short period of time the CircuitBreaker opens.

**Comment by BVBlove9** [comment]
if now the failureRateThreshold is 60% and the slowCallRateThreshold is 60%. window is 4. now we have 2 fail and 2 slowcall. so the current failureRate is 50% and current slowCallRate is 50%. so the circuitbreaker is still close.Is there a problem here?

**Comment by RobWin** [comment]
No, because only 2 calls have been slow, but still successful and 2 calls failed, but not because of a timeout exception.

**Comment by BVBlove9** [comment]
But i still have some problems.The resilence4j set the default slowCallRateThreshhold value with 100%.Now suppose the window size is 100,and failureRateThreshoud is 50% . Now 99 slow events happens and one fail event happen.In this situation,circuitbreaker consider this service is all right just because it return a failure.

**Comment by BVBlove9** [comment]
In my opinon, if consider a fail as a slow call. Maybe can fix this problem.
