### ISSUE TITLE
adding Variance time to metrics

### ISSUE THREAD

**Issue by pwanish** [resilience4j/resilience4j#685]
average and max of an interval lacks a lot of information. Adding variance (aka standard deviation) can address this. Jitter is the best precuror to bad events and great for tuning the most limiting controls. 
What is missing is the accumulation of square of the DurationInMillis time. Since I don't have test environment, I coded it (in "metrics"), for anyone else to add next time they touch "metrics". 
This would expose: 
public Duration getAverageDurationVariance() (close estimate of variance) and/or 
public Duration getTotalDuration2()  (for consumer to do their own reduction)
to use Duration2, the math is:
IF NumOfCalls<=10 V=0 else V= (duration2/NumOfCalls)-(duration/NumOfCalls)**2)**.5
[resillence4j-varianceAdds.txt](https://github.com/resilience4j/resilience4j/files/3725131/resillence4j-varianceAdds.txt)

**Comment by RobWin** [comment]
Sry, I don't understand what you suggest?
Can you use markdown to format your issue and code snippet. Or create a PR?

**Comment by RobWin** [comment]
If you use our resilience4j-micrometer module, you get a lot of additional metrics like Histograms, Percentiles, ...

**Comment by RobWin** [comment]
Measuring this is not part of the core library. We just measure what we need for the core CircuitBreaker or AdaptiveBulkhead functionality.

**Comment by pwanish** [comment]
Standard deviation cannot be calculated without the metric of SUM(Millis*Mills). I offered both exposing only the SUM, or returning the processes number as the variance. I don't care about that. 
Reference math: https://www.strchr.com/standard_deviation_in_one_pass
Attached file correct, but missed type casting. You want me to attach the 5 java parts (with modified code)?

**Comment by RobWin** [comment]
The micrometer module sends more metrics to Prometheus/InfluxDB.
You should be able to calculate standard deviation there, or?

**Comment by RobWin** [comment]
The Metrics/Snapshot Java Interface wasn't built to provide and calculate you such metrics.

**Comment by pwanish** [comment]
On last comment, this ONLY aggregates a single variable that cannot be obtained, unless an aggregator (the product of two (long)) is added (and exposed. 
You said "markdown to format your issue and code snippet". I know all the exposed metrics, and you cannot calculate the variance. SO I'll assume you'll at least consider if attached code is here... One file, all impacted .java components included. Each java part starts with /*************,   and each segment/snippet labeled with /***   (always slash and three asterisks)._
[resillence4j-varianceParts.txt](https://github.com/resilience4j/resilience4j/files/3731783/resillence4j-varianceParts.txt)

**Comment by RobWin** [comment]
By formatting your issue and code I mean that you should use Markdown in your comments here -> https://guides.github.com/features/mastering-markdown/

Instead of using a txt-file you should either create a GitHub PR -> https://help.github.com/en/articles/creating-a-pull-request

Or copy the code into the comment and format it accordingly -> https://help.github.com/en/articles/creating-and-highlighting-code-blocks

**Comment by RobWin** [comment]
Let my try to explain again:

The classes `AbstractAggregation`, `TotalAggregation` , `Measurement` and `PartialAggregation`  are used internally to track metrics which are required for the functionality of the CircuitBreaker and AdaptiveBulkhead. The classes are optimized for this task and should not measure or calculate anything else. Because the metrics are recalculated on every recorded call and every additional metric decreases the performance.

Actually the total duration and average duration of all calls within a time window is not used anymore and we could remove it. The most important metrics for the CircuitBreaker and Adaptive Bulkhead are the failure rate (`getFailureRate`) and the percentage of calls which were slower than a certain threshold (`getSlowCallRate`).

You shouldn't use the `CircuitBreaker.Metrics` to create a Dashboard to view the average duration or total duration of calls or even standard deviation, because they only show it for the current sliding time window.

We created a [Micrometer module ](https://micrometer.io/) for that. Micrometer provides vendor-neutral interfaces for timers, gauges, counters, distribution summaries with a dimensional data model. You can push/pull metrics to Prometheus or InfluxDB. Based on the stored historical data you can calculate almost everything. There are a lot of aggregration functions available -> https://prometheus.io/docs/prometheus/latest/querying/functions/
You can calculate the mean duration of all calls of a certain time interval and also the standard deviation.
I hope it is more clear now.
