### ISSUE TITLE
Backward incompatible version with minor version change

### ISSUE THREAD

**Issue by laksnv** [resilience4j/resilience4j#846]
I went through the release notes of [v1.3.0](https://github.com/resilience4j/resilience4j/releases/tag/v1.3.0) and it seems like there's a non-backward compatible change that's been introduced: https://github.com/resilience4j/resilience4j/pull/831

I assumed Resilience4j uses semantic versioning but couldn't find this in the documentation. Could you please confirm if this is true and clarify why the version wasn't bumped to 2.0?

**Comment by RobWin** [comment]
Yes and no, we are somehow using semantic versioning. We usually increase the minor version when we introduced new features and the bugfix version when we fixed bugs. But this non backward compatible change in an API which returns CompletableFuture<Void>  instead of void now wasn't a reason for us/me to increase the major version.
