### ISSUE TITLE
Retry.decorateEitherSupplier with E param not restricted to Exceptions

### ISSUE THREAD

**Issue by galegofer** [resilience4j/resilience4j#898]
Hi there,

First, thanks for the incredible work that you are doing here.

I am creating this non-issue, in order to check if it has sense when you are creating a Retry from Vavr Eithers to make the E param to extends from Exception.

`static <**E extends Exception**, T> decorateEitherSupplier(Retry retry, Supplier<Either<E, T>> supplier)`

I am saying that because, what about if that E is a Throwable, Error or even just a type that I define in my project to signal that something bad happens, but I want to avoid using explicitly an Exception and make the retry happen just because I am receiving a Left part no matter what's inside?.

Could be possible to have another method that receives an Either, but just with <E, T> with E unbounded?. Does it make sense?.

Thanks!.

Resilience4j version: (resilience4j-retry)
1.3.1
Java version:
1.8.0_231

**Comment by RobWin** [comment]
Hi,
thank you.
Currently Retry and CircuitBreaker react on exceptions. That means they catch exceptions and check if the exception should be retried or should increase the failure rate. 
For example HttpClientExceptions are usually ignored.

It might be confusing to users if the retry happens just because Either is Left.
It means they couldn't skip retry attempts based on the exception type of the Left part.
But the decorator is simple. You could easily implement your own on top of Resilience4j. We designed Resilience4j especially for extensibility .


```
    static <E, T> Supplier<Either<E, T>> decorateEitherSupplier(Retry retry,
                                                                                  Supplier<Either<E, T>> supplier) {
        return () -> {
            Retry.Context<T> context = retry.context();
            do {
                Either<E, T> result = supplier.get();
                if (result.isRight()) {
                    final boolean validationOfResult = context.onResult(result.get());
                    if (!validationOfResult) {
                        context.onComplete();
                        return result;
                    }
                } else {
                    try {
                        context.onError(new EitherIsLeftException());
                    } catch (Exception e) {
                        return result;
                    }
                }
            } while (true);
        };
    }
```

I think you shouldn't propagate Errors through the system (by using Either/Try), but instead throw it. 
> An Error  indicates serious problems that a reasonable application should not try to catch. Most such errors are abnormal conditions.
Vavr shouldn't even allow to create Either/Try containting Errors.

**Comment by galegofer** [comment]
Hi Robert,

Thanks for the quick answer!.
I agree with what you said about that it may be confusing to the users and it may lead to misunderstandings.
Anyway, if you think about it from the functional programming point, there there is no such thing as an "Exception", but a failure in the computation, I mean like a concept, that's why Vavr Either is designed how it is designed, not forcing any assumption on the left side type.
So in my interpretation, to retry based on a left makes sense, due to some computation failed and the operation must be re-attempted, it should be fine.
Anyway, I understand where are you pointing to the library, so just giving my 20 cents.
Thank you very much for the example code and keep it up the great work that you are doing here!.

**Comment by RobWin** [comment]
I totally agree with your point. 
The library was also designed to be used outside of a functional programming paradigm.
In order to better support Either and custom Left data types, we would need to add additional predicates to supports checks on custom types. For example Either could be Left, but you don't want to retry on that specific Left, because it signals a Client-side HTTP problem.

**Comment by Romeh** [comment]
ok closing the ticket as nothing more is required from our side , feel free to open new issue if you have new questions
