### ISSUE TITLE
Think about making rxjava and javaslang optional

### ISSUE THREAD

**Issue by drmaas** [resilience4j/resilience4j#90]
It might make sense to move the rx stuff and javaslang wrappers into separate modules so people not using them will not have to consume them. Thoughts?

**Comment by RobWin** [comment]
This was discussed in #51.
The issue is that the CircuitBreaker, RateLimiter and Retry emit a hot stream of events and we needed a good and working ReactiveStreams processor implementation. ReactiveStreams does not provide implementations, but only Interfaces.
But we could use the ServiceLoader to load an implementation at runtime. Users could choose to use RxJava or Spring Reactor.

We use Javaslang heavily. This is harder to replace.

**Comment by drmaas** [comment]
Good to know, I was not aware javaslang was used so heavily. 

I was reading about https://github.com/jhalterman/failsafe and saw they had 0 dependencies and some other builder patterns for specifying and reacting to circuitbreaker and retry events.

**Comment by RobWin** [comment]
Yes, my design decision was not to implement thousands of event listener callback methods for all event types, but instead emit a stream of events which a client can subscribe to and handle the events on a scheduler of his choice..

**Comment by RobWin** [comment]
My second design decision was to implement a library which is suitable for "functional programming"  and Javaslang was my long-term bet. Javaslang has no dependencies. So it should not be too heavyweight. It also reduces the barrier for users to apply functional programming.

**Comment by RobWin** [comment]
FailSafe is the option for users who do not want to use Functional Programming (Javaslang) or Reactive Streams. But I think both programming styles are the future of programming.

**Comment by drmaas** [comment]
👍  Thanks for the explanation. I think it would be helpful to capture those intentions and design decisions in the README or the website.

**Comment by drmaas** [comment]
Closing, as this does not seem to align with project design principles.
