### ISSUE TITLE
Question about TimeLimiter and method return types

### ISSUE THREAD

**Issue by shi-314** [resilience4j/resilience4j#948]
Resilience4j 1.3.1:

Java 11:

Hi,

I am using Resilience4J along with Spring Boot and Kotlin and I am wondering whether it's possible to use the `@TimeLimiter` annotation without changing the methods return type to return a `CompleteableFuture`. Is there a reason why the `@Bulkhead` and `@CircuitBreaker` annotations do not require a Future object to be returned but the TimeLimiter?

Best regards,
Shivan

**Comment by hexmind** [comment]
Hi,
you can also choose reactive types like Flux or Mono from Spring Reactor (or RxJava 2 counterparts).
In other way your solution would be written in a blocking manner.
Another reason is an internal implementation of `@TimeLimiter` or `@Bulkhead(type = THREADPOOL)`. Because of added "time dimension" they are also work thanks `CompleteableFuture` or reactive way.

**Comment by shi-314** [comment]
I can understand that there are technical reasons why the library needs to execute the method inside of a `CompletableFuture` but do you see any way to use the TimeLimiter without changing the methods signatures? As a user of your API I would appreciate it if I could just annotate my methods without changing their signatures.

But you are right, the method would be implemented in a blocking way in that case.

**Comment by hexmind** [comment]
What comes to mind is creating an adapter that executes `.get(timeout, TimeUnit.SECONDS)` unwrapping a `Future`. But it's just a workaround.

**Comment by shi-314** [comment]
Thanks for your help @hexmind. I think I can work around it now and it seems that the library is designed to be applied on non-blocking calls which might be a good idea anyway.
