### ISSUE TITLE
Threshold for slowCalls to be treated as timeout

### ISSUE THREAD

**Issue by ravichauhan03** [resilience4j/resilience4j#973]
Resilience4j version:
1.4.0

Java version:
1.8

Thanks for raising a Resilience4j issue.
We are trying to configure the timeout for the slow calls which is to be treated as failures and open the circuit. I went through a couple of articles but did not get my answers. Therefore, just wanted to confirm if it is even possible to do so? If yes, can you share some examples around it?

**Comment by ravichauhan03** [comment]
@RobWin : I saw you response on one of the threads related to this. Requesting your update.

**Comment by RobWin** [comment]
The CircuitBreaker has not option to configure timeouts for slow calls. 
It's the task of the `TimeLimiter`. If you need to treat timeouts as exceptions, you have to combine the CircuitBreaker with the TimeLimiter. But it only works for async calls with Spring Reactor or CompletableFuture.
The slow call rate in the CircuitBreaker allows to OPEN the CircuitBreaker when too many calls are above a response time threshold. This threshold should be below your timeout value. You can open the CircuitBreaker in order to prevent too many timeout exceptions when the remote systems gets unresponsive.

**Comment by ravichauhan03** [comment]
@RobWin : We are wrapping an okhttp call in circuit breaker which is synchronous. So how can we timeout the calls that are slow using resilience4j? As of now, we are timing out from the httpClient.

**Comment by RobWin** [comment]
You should configure your connection, write/read and call timeouts in your OkHttpClient.

```
private val client: OkHttpClient = OkHttpClient.Builder()
      .connectTimeout(5, TimeUnit.SECONDS)
      .writeTimeout(5, TimeUnit.SECONDS)
      .readTimeout(5, TimeUnit.SECONDS)
      .callTimeout(10, TimeUnit.SECONDS)
      .build()
```

Resilience4j TimeLimiter can't timeout/cancel synchronous calls, because the TimeLimiter can't timeout/cancel the thread it is running on. It can only timeout a call which is running in a separate thread.
The CircuitBreaker can only measure response times and open the when too many calls are slow.

**Comment by ravichauhan03** [comment]
@RobWin : Thanks for the clarification. Closing the thread.
