### ISSUE TITLE
Events are not published when "retryOnResult" used in resilience4j for retry based on result not exception

### ISSUE THREAD

**Issue by sandip1805** [resilience4j/resilience4j#978]
Resilience4j version: 1.4.0

Java version: 1.8.0

Thanks for raising a Resilience4j issue.
Whenever i tried to used retryOnResult method for predicate for retry, i am not getting events in my eventlistener, but when i used retryOnException, I am able to get events.
Even I am not able to find any junit related to event with completableFuture, so can you please help me to solve this issue?

```
RetryConfig config = RetryConfig.<String>custom()
                .maxAttempts(3)
                .intervalFunction(IntervalFunction.ofExponentialBackoff(Duration.ofMillis(1000)))
                .retryOnResult(response -> StringUtils.isNotBlank(response))
                .build();
        return RetryRegistry.of(config);
```

```
Retry retry = retryRegistry.retry("retry-[" + data.getMessageId() + "]");

        retry.getEventPublisher()
                .onRetry(retryEvent -> {
                    log.info("retryEvent: {}", retryEvent);
                })
                .onError(errorEvent -> {
                    log.info("errorEvent: {}", errorEvent);
                })
                .onSuccess(successEvent -> {
                    log.info("successEvent: {}", successEvent);
                })
        ;

        CompletionStage<String> responseCompletionStage = retry.executeCompletionStage(scheduledExecutorService, () -> callServiceClient(headers, data));
```

**Comment by Romeh** [comment]
@sandip1805  you check the unit test example here https://github.com/resilience4j/resilience4j/blob/master/resilience4j-retry/src/test/java/io/github/resilience4j/retry/internal/CompletionStageRetryTest.java#L111 

which show u an example of async retry on result , if register your event consumer before invoking the call it should be triggered , in that example it will be onError u will see an event being triggered as retry failed after max retry attempts due to retry on result checkl

**Comment by Romeh** [comment]
closing the issue please if u have any new question create a new one
