### ISSUE TITLE
Fail to match global fallback method

### ISSUE THREAD

**Issue by liting-zhang** [resilience4j/resilience4j#992]
Resilience4j version: 0.17.0

Java version: java 8

I have methods that have the same return type, but with different arguments, and I define a global fallback method like this:

private String fallBack(Throwable throwable) {
   ....
}

for a method that have same return type but more than one argument, it will cause a WrongNumberArgument exception, so how the global fallback works, I can't find any example?

And if I define one more fallback with the extra arguments, it will cause an error saying that more than one fallback method found, so I am confuse here. Can anyone help?

And what's more, I have methods that with same number of arguments but with different return types, so how can I make fallback works in this situation?

**Comment by hexmind** [comment]
Let's suppose your have `public String testMethod(String parameter)` with `fallbackMethod = "fallbackMethod"` defined.
There is an example of correct global fallback:
```
        public String fallbackMethod(Throwable exception) {
            return "global";
        }
```
But you can't define concrete and global fallbacks together because `You have more that one fallback method that cover the same exception type` (exception will be thrown):
```
        // incorect setup
        public String fallbackMethod(String parameter, Throwable exception) {
            return "recovered";
        }

        public String fallbackMethod(Throwable exception) {
            return "global";
        }
```
Methods with different return types are considered separately. Each return type group requires own fallback because fallback "must have the same method signature with just ONE extra target exception parameter" (or only Exception argument for global fallback) https://resilience4j.readme.io/docs/getting-started-3#section-annotations
